# This workflow will do a will make issues from todos comments in my project

name: Auto Commit Settings

on:
    push:
        branches: ["master"]
    schedule:
        - cron: "*/1 * * * *"

jobs:
    auto-commit:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Verifying Repository
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}
            - name: Auto-Commit
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: Automated Commit Change
