# This workflow will send an e-mail (better description coming soon)

name: Making Issues From Todos

on:
    push:
        branches: ["develop"]

jobs:
    send-email:
        runs-on: ubuntu-latest
        steps:
            - name: Accessing & Verifying Repository
              uses: actions/checkout@v3
            - name: Send mail
              uses: dawidd6/action-send-mail@v3
              with:
                  server_address: ${{secrets.EMAIL_SERVER_ADDRESS}}
                  server_port: 465
                  username: ${{secrets.EMAIL_SERVER_USERNAME}}
                  password: ${{secrets.EMAIL_SERVER_PASSWORD}}
                  #   subject: ${{matrix.subject}}
                  subject: "Testing Email"
                  # body: ${{matrix.body}}
                  # html_body: ${{matrix.html_body}}
                  html_body: |
                      <!DOCTYPE html>
                      <html>
                      <body>
                      <h1>Heading</h1>
                      <p>Paragraph</p>
                      </body>
                      </html>
                  to: tsurwagilbert@gmail.com, gtsurwa@su.edu
                  from: tsurwagilbert@gmail.com
                  # attachments: ${{matrix.attachments}}
                  # convert_markdown: ${{matrix.convert_markdown}}
                  attachments: package.json
