# This workflow will do a will make issues from todos comments in my project

name: Making Issues From Todos

on:
    push:
        branches: ["develop"]

jobs:
    check-todos:
        runs-on: ubuntu-latest

        steps:
            - name: Verifying Repository
              uses: actions/checkout@v3
            - name: Send mail
              uses: ./
              with:
                  #   server_address: ${{secrets.ADDRESS}}
                  server_address: smtp.gmail.com
                  server_port: 465
                  #   username: ${{secrets.USERNAME}}
                  username: ${{secrets.USERNAME}}
                  #   password: ${{secrets.PASSWORD}}
                  password: ${{secrets.PASSWORD}}
                  #   subject: ${{matrix.subject}}
                  subject: "Testing Testing Yoyyoyo One One"
                  # body: ${{matrix.body}}
                  body: "Ça c'est un test courriel"
                  # html_body: ${{matrix.html_body}}
                  html_body: "<h1>Ça c'est un test de courriel</h1>"
                  to: ${{github.event.pusher.email}}
                  from: github-actions
                  # attachments: ${{matrix.attachments}}
                  # convert_markdown: ${{matrix.convert_markdown}}
                  priority: high
